# Generated by Django 5.2.8 on 2025-12-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolyear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la classe, ex: 6ème A', max_length=50)),
                ('main_teacher', models.ForeignKey(blank=True, help_text='Professeur principal de la classe', limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_classes', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, help_text='Autres enseignants de la classe', limit_choices_to={'role': 'TEACHER'}, related_name='classes_teaching', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(help_text='Année scolaire à laquelle appartient la classe', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schoolyear.schoolyear')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
                'unique_together': {('name', 'year')},
            },
        ),
    ]
