# Generated by Django 5.2.8 on 2025-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/photos/default.png', null=True, upload_to='users/photos/'),
        ),
    ]
