# Generated by Django 5.2.8 on 2025-11-16 10:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/photos/default.jpg', null=True, upload_to=accounts.models.user_photo_path),
        ),
    ]
