# Generated by Django 5.2.8 on 2025-12-03 14:15

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=attendance.models.get_current_time),
        ),
    ]
